name: Build and Sign amneziawg-apple

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    name: Build and Sign for macOS
    runs-on: macos-latest

    # This is the fix: Set the default working directory for all run steps in this job
    defaults:
      run:
        working-directory: ./amneziawg-apple

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      # The checkout action creates a directory named after the repo, so we need to cd into it.
      # The 'path' property here explicitly names that directory.
      with:
        path: amneziawg-apple

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        # Tell the ruby action where to find the Gemfile
        working-directory: ./amneziawg-apple

    - name: Install SwiftLint
      run: |
        brew install swiftlint
      # This step does not need the working directory as it's a global install

    - name: Import Signing Certificate
      run: |
        echo "${{ secrets.P12_BASE64 }}" | base64 --decode > certificate.p12
        security create-keychain -p "${{ secrets.P12_PASSWORD }}" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "${{ secrets.P12_PASSWORD }}" build.keychain
        security import certificate.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.P12_PASSWORD }}" build.keychain
        rm certificate.p12

    - name: Run Fastlane to Setup Signing
      env:
        FASTLANE_USER: ${{ secrets.APPLE_ID_USERNAME }}
        FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_APP_SPECIFIC_PASSWORD }}
        FASTLANE_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
      run: |
        bundle exec fastlane setup_signing

    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Build and Sign macOS application
      run: |
        # IMPORTANT: Use the same unique identifier as in your Fastfile
        xcodebuild -project WireGuard.xcodeproj \
                   -target "WireGuardmacOS" \
                   -configuration Release \
                   build \
                   CODE_SIGN_STYLE="Manual" \
                   DEVELOPMENT_TEAM="${{ secrets.APPLE_DEVELOPER_TEAM_ID }}" \
                   CODE_SIGN_IDENTITY="Apple Development" \
                   PRODUCT_BUNDLE_IDENTIFIER="com.your-github-username.amneziawg" \
                   OTHER_LDFLAGS="-lresolv"

    - name: Upload macOS Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: AmneziaWG-macOS-Signed
        # The path to the artifact is now relative to the working-directory
        path: amneziawg-apple/build/Release/WireGuardmacOS.app
