name: Find Xcode Schemes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  find-schemes:
    name: List available Xcode schemes
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List schemes
      run: |
        xcodebuild -list -project WireGuard.xcodeproj
