name: Build and Sign amneziawg-apple

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    name: Build and Sign for macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Create Developer.xcconfig with Team ID
      run: |
        echo "DEVELOPMENT_TEAM = ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}" > Sources/WireGuardApp/Config/Developer.xcconfig

    - name: Import Signing Certificate
      run: |
        # Create a temporary keychain
        security create-keychain -p "${{ secrets.P12_PASSWORD }}" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "${{ secrets.P12_PASSWORD }}" build.keychain
        
        # Decode the certificate from the GitHub Secret
        echo "${{ secrets.P12_BASE64 }}" | base64 --decode > Certificates.p12
        
        # Import the certificate into the keychain
        security import Certificates.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign
        
        # Allow codesigning from the keychain
        security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.P12_PASSWORD }}" build.keychain
        
        # Clean up the certificate file
        rm Certificates.p12

    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Build and Sign macOS application
      run: |
        # Build with signing enabled, letting Xcode find the certificate automatically
        xcodebuild -project WireGuard.xcodeproj \
                   -target "WireGuardmacOS" \
                   -configuration Release \
                   build \
                   OTHER_LDFLAGS="-lresolv"

    - name: Upload macOS Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: AmneziaWG-macOS-Signed
        path: build/Release/WireGuardmacOS.app
