name: Build and Upload amneziawg-apple (No Signing)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Homebrew dependencies
      uses: actions/cache@v3
      with:
        path: /usr/local/Homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Create Developer.xcconfig from template
      run: |
        cp Sources/WireGuardApp/Config/Developer.xcconfig.template Sources/WireGuardApp/Config/Developer.xcconfig

    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Build macOS application without signing
      run: |
        xcodebuild -project WireGuard.xcodeproj -target "WireGuardmacOS" -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO OTHER_LDFLAGS="-lresolv"

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AmneziaWG-macOS
        path: /Users/runner/work/amneziawg-apple/amneziawg-apple/build/Release/AmneziaWG.app

  build-ios:
    name: Build for iOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Homebrew dependencies
      uses: actions/cache@v3
      with:
        path: /usr/local/Homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Create Developer.xcconfig from template
      run: |
        cp Sources/WireGuardApp/Config/Developer.xcconfig.template Sources/WireGuardApp/Config/Developer.xcconfig

    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Build iOS application without signing
      run: |
        xcodebuild -project WireGuard.xcodeproj -target "WireGuardiOS" -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO OTHER_LDFLAGS="-lresolv"

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AmneziaWG-iOS
        path: build/Release-iphoneos/WireGuardiOS.app
